version: "3.8"

services:

  quartz:
    build:
      context: .
    image: $QUARTZ_IMAGE
    container_name: quartz
    ports:
      - 8080:8080
    volumes:
    - type: bind
      source: $QUARTZ_DIR
      target: /data

  noske:
    image: $NOSKE_IMAGE
    container_name: noske
    volumes:
      - type: bind
        source: $CORPORA_DIR
        target: /corpora
    ports:
      - 10070:80
