version: "3.8"

services:

  quartz:
    build:
      context: .
    image: $IMAGE
    container_name: $CONTAINER
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: $CONFIG_DIR
        target: /code/config
      - type: bind
        source: $DATA_DIR
        target: /code/data
    env_file:
      - .env
