# settings for corpora
# corpus name used by API
susanne:
  # name shown in graphs
  name: Susanne
  # unique color code
  color: "#636EFA"
  # corpus description file (optional)
  md_file: config/susanne.md
  # text types to exclude
  exclude:
    - doc.wordcount
    - font.type
  # text type labels (required for every non-excluded text type/attribute)
  label:
    doc.file: file
    doc.n: "n"
    head.type: head
  # text types considered comparable with other corpora
  # comparable:
    # - <VALUE>
  # text types to visualize w/ choropleth (requires ISO3 strings, case insensitive)
  # choropleth:
    # - <VALUE>
